using System.Globalization;
using System.Collections.ObjectModel;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Mt5Manager.Application.Abstractions;
using Mt5Manager.Domain.Models;
namespace Mt5Manager.Wpf.ViewModels;
public sealed partial class MainViewModel(ITerminalDiscovery discovery,ITerminalRegistry registry,ITerminalProcessController process,ITerminalRuntimeInspector? runtime=null,IAlgoTradingService? algo=null,ITerminalStorageInspector? storage=null,IAuditLogger? audit=null,IBridgeInstaller? bridge=null,ITerminalUpdateService? update=null):ObservableObject
{
 readonly List<TerminalRowViewModel> all=[];CancellationTokenSource? refresh;int stateRefreshActive;
 [ObservableProperty][NotifyPropertyChangedFor(nameof(VisibleCount),nameof(SummaryText))] string searchText="";
 [ObservableProperty][NotifyPropertyChangedFor(nameof(VisibleCount),nameof(SummaryText))] string stateFilter="All";
 [ObservableProperty] bool isRefreshing;[ObservableProperty]string? error;[ObservableProperty]TerminalRowViewModel? selectedTerminal;
 public ObservableCollection<TerminalRowViewModel> Terminals{get;}=[];
 public IReadOnlyList<TerminalRegistration> AllRegistrations=>all.Select(x=>x.Terminal).ToArray();
 public int TotalCount=>all.Count;public int VisibleCount=>Terminals.Count;
 public string SummaryText=>TotalCount==0?"No terminals registered":$"{VisibleCount} of {TotalCount} terminals shown";
 public string[] StateFilters=>["All","Running","Stopped","Needs attention"];
 public bool IsBatchIdle=>!IsBatchBusy&&!IsRefreshing;
 public bool HasBatchSelection=>all.Any(x=>x.IsBatchSelected);
 public string SelectionSummary=>$"{all.Count(x=>x.IsBatchSelected)} selected"+(all.Any(x=>x.IsBatchSelected&&!Terminals.Contains(x))?" (includes hidden terminals)":"");
 public string EmptyStateText=>all.Count==0?"Scan for MT5 terminals or add a terminal to get started.":"No terminals match these filters. Clear search or choose All.";
 partial void OnIsRefreshingChanged(bool value)=>OnPropertyChanged(nameof(IsBatchIdle));
 partial void OnSearchTextChanged(string value)=>ApplyFilter();
 partial void OnStateFilterChanged(string value)=>ApplyFilter();
 void OnRowPropertyChanged(object? sender,System.ComponentModel.PropertyChangedEventArgs e){if(e.PropertyName==nameof(TerminalRowViewModel.IsBatchSelected)){OnPropertyChanged(nameof(HasBatchSelection));OnPropertyChanged(nameof(SelectionSummary));}}
 [ObservableProperty] bool isBatchBusy;
 [ObservableProperty] string batchStatus="Select terminals with their checkboxes to manage sessions together.";
 public bool CanUseWorkspace=>!IsBatchBusy;
 partial void OnIsBatchBusyChanged(bool value){OnPropertyChanged(nameof(CanUseWorkspace));OnPropertyChanged(nameof(IsBatchIdle));OnPropertyChanged(nameof(SelectionSummary));}
 public ObservableCollection<BatchSessionResult> BatchResults{get;}=[];
 public TerminalRowViewModel[] SnapshotSelection()=>all.Where(x=>x.IsBatchSelected).GroupBy(x=>x.Terminal.Id).Select(x=>x.First()).ToArray();
 [RelayCommand] void ClearSelection(){foreach(var row in all)row.IsBatchSelected=false;}
 public async Task RunUpdateAsync(IReadOnlyList<TerminalRowViewModel> targets,CancellationToken token=default){if(IsBatchBusy||IsRefreshing)return;if(update is null){BatchStatus="Update service is unavailable.";return;}var snapshot=targets.GroupBy(x=>x.Terminal.Id).Select(x=>x.First()).ToArray();if(snapshot.Any(x=>x.IsBusy)){BatchStatus="Wait for selected terminal operations to finish before updating.";return;}IsBatchBusy=true;var reserved=all.Where(x=>!x.IsBusy).ToArray();foreach(var row in reserved)row.IsBusy=true;BatchResults.Clear();try{var progress=new Progress<UpdateProgress>(p=>{BatchStatus=$"Update: {p.Completed} of {p.Total}";if(p.Result is { } r)BatchResults.Add(new(r.TerminalName,r.Skipped?"Skipped":r.Success?"Completed":"Failed",r.Message));});await update.UpdateAsync(new(snapshot.Select(x=>x.Terminal).ToArray()),progress,token);foreach(var row in snapshot)await row.RefreshStateAsync(CancellationToken.None);BatchStatus=token.IsCancellationRequested?"Update cancelled; review recovery results.":"Sequential update finished. Review evidence; latest version is not guaranteed.";}catch(Exception ex){BatchStatus=$"Update failed: {ex.Message}";}finally{foreach(var row in reserved)row.IsBusy=false;IsBatchBusy=false;}}
 public async Task RunBatchAsync(string operation,IReadOnlyList<TerminalRowViewModel> targets){if(IsBatchBusy||IsRefreshing){BatchStatus=$"{operation} could not start while another scan or batch is active.";return;}var snapshot=targets.GroupBy(x=>x.Terminal.Id).Select(x=>x.First()).ToArray();IsBatchBusy=true;BatchResults.Clear();try{for(var index=0;index<snapshot.Length;index++){var row=snapshot[index];BatchStatus=$"{operation}: {index+1} of {snapshot.Length} — {row.DisplayName}";if(row.IsBusy){BatchResults.Add(new(row.DisplayName,"Skipped","This terminal is busy; retry after its current operation finishes."));continue;}var allowed=operation switch{"Start"=>row.CanStart,"Stop"=>row.CanStop,"Restart"=>row.CanRestart,_=>false};if(!allowed){BatchResults.Add(new(row.DisplayName,"Skipped","Not ready for this operation; inspect this terminal's state and verified data folder."));continue;}switch(operation){case "Start":await row.StartAsync();break;case "Stop":await row.StopAsync();break;case "Restart":await row.RestartAsync();break;}BatchResults.Add(new(row.DisplayName,row.Error is null?"Succeeded":"Failed",row.Error??row.LastResult??"Operation completed."));ApplyFilter();}BatchStatus=$"{operation} completed: {BatchResults.Count(x=>x.Outcome=="Succeeded")} succeeded, {BatchResults.Count(x=>x.Outcome=="Failed")} failed, {BatchResults.Count(x=>x.Outcome=="Skipped")} skipped.";}finally{IsBatchBusy=false;ApplyFilter();}}
 [RelayCommand]public async Task RefreshAsync(){if(IsBatchBusy){BatchStatus="Refresh is unavailable while a batch is running.";return;}refresh?.Cancel();var owner=new CancellationTokenSource();refresh=owner;IsRefreshing=true;Error=null;var selectedId=SelectedTerminal?.Terminal.Id;try{var found=await discovery.DiscoverAsync(owner.Token);var candidates=found.Select(x=>new TerminalRowViewModel(x,process,runtime,algo,storage,audit,bridge)).ToArray();await Task.WhenAll(candidates.Select(async x=>{await x.RefreshStateAsync(owner.Token);await x.LoadOperationHistoryAsync(owner.Token);}));if(ReferenceEquals(refresh,owner)){var existing=all.ToDictionary(x=>x.Terminal.Id);var rows=candidates.Select(candidate=>{if(existing.TryGetValue(candidate.Terminal.Id,out var row)&&RegistrationsEqual(row.Terminal,candidate.Terminal)){row.ApplyRefreshSnapshot(candidate);return row;}return candidate;}).ToArray();foreach(var row in all)row.PropertyChanged-=OnRowPropertyChanged;all.Clear();all.AddRange(rows);foreach(var row in all)row.PropertyChanged+=OnRowPropertyChanged;ApplyFilter(selectedId);}}catch(OperationCanceledException)when(owner.IsCancellationRequested){}catch(Exception ex){if(ReferenceEquals(refresh,owner))Error=ex.Message;}finally{if(ReferenceEquals(refresh,owner)){refresh=null;IsRefreshing=false;}owner.Dispose();}}
 static bool RegistrationsEqual(TerminalRegistration left,TerminalRegistration right)=>left.Id==right.Id&&left.DisplayName==right.DisplayName&&left.ExecutablePath==right.ExecutablePath&&left.DataDirectory==right.DataDirectory&&left.WorkingDirectory==right.WorkingDirectory&&left.Arguments.SequenceEqual(right.Arguments)&&left.Source==right.Source&&left.DataDirectoryVerified==right.DataDirectoryVerified;
 void ApplyFilter(Guid? preferredId=null){var selectedId=preferredId??SelectedTerminal?.Terminal.Id;Terminals.Clear();foreach(var row in all.Where(x=>Matches(x)))Terminals.Add(row);SelectedTerminal=Terminals.FirstOrDefault(x=>x.Terminal.Id==selectedId)??Terminals.FirstOrDefault();OnPropertyChanged(nameof(TotalCount));OnPropertyChanged(nameof(VisibleCount));OnPropertyChanged(nameof(SummaryText));OnPropertyChanged(nameof(HasBatchSelection));OnPropertyChanged(nameof(SelectionSummary));}
 bool Matches(TerminalRowViewModel row){var text=SearchText.Trim();var matchesText=text.Length==0||new[]{row.DisplayName,row.ExecutablePath,row.DataDirectory,row.AccountSummary}.Any(value=>value.Contains(text,StringComparison.OrdinalIgnoreCase));return matchesText&&(StateFilter switch{"Running"=>row.State==TerminalState.Running,"Stopped"=>row.State==TerminalState.Stopped,"Needs attention"=>row.State==TerminalState.Error||!row.Terminal.DataDirectoryVerified||row.Account is null||row.Account.Connected==false,_=>true});}
 public async Task AddManualAsync(TerminalRegistration terminal){try{var items=(await registry.LoadAsync()).Where(x=>x.Id!=terminal.Id).Append(terminal).ToArray();await registry.SaveAsync(items);}catch(Exception ex){Error=$"The terminal could not be registered: {ex.Message}";return;}await RefreshAsync();}public void CancelRefresh()=>refresh?.Cancel();
 public async Task RefreshStatesAsync(CancellationToken token=default){if(Interlocked.CompareExchange(ref stateRefreshActive,1,0)!=0)return;try{foreach(var row in all.ToArray()){bool cancelled;try{cancelled=token.IsCancellationRequested;}catch(ObjectDisposedException){cancelled=true;}if(cancelled)return;try{await row.RefreshStateAsync(token);}catch(OperationCanceledException){return;}catch(ObjectDisposedException){return;}}}finally{ApplyFilter();Volatile.Write(ref stateRefreshActive,0);}}
 }
public sealed partial class TerminalRowViewModel(TerminalRegistration terminal,ITerminalProcessController process,ITerminalRuntimeInspector? runtime=null,IAlgoTradingService? algo=null,ITerminalStorageInspector? storage=null,IAuditLogger? audit=null,IBridgeInstaller? bridge=null):ObservableObject
{
    public TerminalRegistration Terminal=>terminal;public string DisplayName=>terminal.DisplayName;public string ExecutablePath=>terminal.ExecutablePath;public string DataDirectory=>terminal.DataDirectory;
    public string GlobalAlgoTradingWarning=>"Global Algo Trading affects every EA in this terminal.";
    public ObservableCollection<OperationLogEntry> OperationHistory{get;}=[];
 [ObservableProperty] bool isBatchSelected;
    [ObservableProperty][NotifyCanExecuteChangedFor(nameof(StartCommand),nameof(StopCommand),nameof(RestartCommand),nameof(EnableAlgoCommand),nameof(DisableAlgoCommand))]TerminalState state=TerminalState.Busy;
    [ObservableProperty][NotifyCanExecuteChangedFor(nameof(StartCommand),nameof(StopCommand),nameof(RestartCommand),nameof(EnableAlgoCommand),nameof(DisableAlgoCommand),nameof(InspectStorageCommand),nameof(InstallBridgeCommand))][NotifyPropertyChangedFor(nameof(CanCleanup),nameof(CanInspectStorage),nameof(CanEnableAlgo),nameof(CanDisableAlgo),nameof(CanInstallBridge))]bool isBusy;
    [ObservableProperty][NotifyCanExecuteChangedFor(nameof(EnableAlgoCommand),nameof(DisableAlgoCommand))]TerminalAccountSnapshot? account;
    [ObservableProperty]string? error;[ObservableProperty]int? processId;[ObservableProperty]string storageSummary="Storage not inspected";[ObservableProperty]string lastResult="No operations yet";
    [ObservableProperty]string accountSummary="Bridge unavailable";[ObservableProperty]string algoSummary="Algo Trading unknown";[ObservableProperty]string bridgeInstallSummary="Bridge installation unknown";[ObservableProperty]bool isBridgeInstallVisible=true;
 public string ReadinessGuidance=>!terminal.DataDirectoryVerified?"Verify this terminal's folder using MT5 File → Open Data Folder before stopping, installing the bridge or cleaning files.":State==TerminalState.Stopped?"Start this terminal, then connect to your broker inside MT5.":Account is null?"Install the bridge and attach its EA to an MT5 chart. Keep MT5 and that chart running; scan again for fresh account status.":$"Account status: {AccountSummary}. Broker login is managed inside MT5; Algo Trading is a separate permission for EAs.";
 partial void OnStateChanged(TerminalState value)=>OnPropertyChanged(nameof(ReadinessGuidance));
 partial void OnAccountChanged(TerminalAccountSnapshot? value)=>OnPropertyChanged(nameof(ReadinessGuidance));
    public bool CanStart=>!IsBusy&&State is TerminalState.Stopped or TerminalState.Error;public bool CanStop=>!IsBusy&&terminal.DataDirectoryVerified&&!string.IsNullOrWhiteSpace(terminal.DataDirectory)&&State==TerminalState.Running;public bool CanRestart=>CanStop;public bool CanCleanup=>!IsBusy&&terminal.DataDirectoryVerified&&!string.IsNullOrWhiteSpace(terminal.DataDirectory);public bool CanInspectStorage=>!IsBusy&&terminal.DataDirectoryVerified&&storage is not null;public bool CanInstallBridge=>!IsBusy&&bridge is not null&&terminal.DataDirectoryVerified&&!string.IsNullOrWhiteSpace(terminal.DataDirectory);
    public bool CanEnableAlgo=>CanControlAlgo&&Account?.GlobalAlgoTrading is AlgoTradingState.Disabled;
    public bool CanDisableAlgo=>CanControlAlgo&&Account?.GlobalAlgoTrading is AlgoTradingState.Enabled;
    bool CanControlAlgo=>!IsBusy&&State==TerminalState.Running&&runtime is not null&&algo is not null&&terminal.DataDirectoryVerified&&Account is not null&&Account.GlobalAlgoTrading!=AlgoTradingState.Unknown;
    [RelayCommand(CanExecute=nameof(CanStart))]public async Task StartAsync()=>await Run(async()=>{ProcessId=await process.StartAsync(terminal,CancellationToken.None);State=TerminalState.Running;LastResult="Terminal started.";},operationName:"Start");
    [RelayCommand(CanExecute=nameof(CanStop))]public async Task StopAsync()=>await Run(async()=>{var r=await process.StopAsync(terminal,TimeSpan.FromSeconds(15),false,CancellationToken.None);if(r.Outcome is StopOutcome.ExitedGracefully or StopOutcome.AlreadyStopped or StopOutcome.ForceTerminated){State=TerminalState.Stopped;ProcessId=null;LastResult=r.Outcome.ToString();return;}await RefreshActualStateAsync();throw new InvalidOperationException(r.Error??$"Terminal stop {r.Outcome.ToString().ToLowerInvariant()}.");},operationName:"Stop");
    [RelayCommand(CanExecute=nameof(CanRestart))]public async Task RestartAsync()=>await Run(async()=>{var stopped=await process.StopAsync(terminal,TimeSpan.FromSeconds(15),false,CancellationToken.None);if(stopped.Outcome is not (StopOutcome.ExitedGracefully or StopOutcome.AlreadyStopped or StopOutcome.ForceTerminated)){await RefreshActualStateAsync();throw new InvalidOperationException(stopped.Error??$"Terminal stop {stopped.Outcome.ToString().ToLowerInvariant()}; restart canceled.");}ProcessId=await process.StartAsync(terminal,CancellationToken.None);State=TerminalState.Running;LastResult="Terminal restarted.";},operationName:"Restart");
    [RelayCommand(CanExecute=nameof(CanEnableAlgo))]public async Task EnableAlgoAsync(CancellationToken token=default)=>await SetAlgoAsync(true,token);
    [RelayCommand(CanExecute=nameof(CanDisableAlgo))]public async Task DisableAlgoAsync(CancellationToken token=default)=>await SetAlgoAsync(false,token);
    [RelayCommand]public Task RefreshStateAsync()=>RefreshStateAsync(CancellationToken.None);
    [RelayCommand(CanExecute=nameof(CanInspectStorage))]public async Task InspectStorageAsync()=>await RunStorageInspectionAsync();
    [RelayCommand(CanExecute=nameof(CanInstallBridge))]public async Task InstallBridgeAsync()=>await Run(async()=>{var result=await bridge!.InstallAsync(terminal,CancellationToken.None);ProjectBridgeState(result.Status);if(!result.Success)throw new InvalidOperationException(result.Message);LastResult=result.Message;},operationName:"Install bridge");
    public async Task RefreshStateAsync(CancellationToken token)=>await Run(async()=>{var s=await process.GetStateAsync(terminal,token);State=s.State;ProcessId=s.ProcessId;Error=s.Error;if(runtime is not null){Account=await runtime.ReadAsync(terminal,token);ProjectRuntimeState();}if(bridge is not null)ProjectBridgeState(await bridge.InspectAsync(terminal,token));},token);
    public async Task RunStorageInspectionAsync(){if(storage is null)return;await Run(async()=>ApplyStorageInspection(await storage.InspectAsync(terminal,CancellationToken.None)),preserveLastResult:true);}
    public void ApplyStorageInspection(IReadOnlyList<CategoryUsage> usage)=>StorageSummary=string.Join(" · ",usage.Select(x=>$"{x.Category}: {x.FileCount:N0} files, {FormatStorageSize(x.Bytes)}"));
    public static string FormatStorageSize(long bytes){string[] units=["B","KB","MB","GB"];var value=(decimal)bytes;var unit=0;while(value>=1024&&unit<units.Length-1){value/=1024;unit++;}return unit==0?$"{bytes} B":$"{value.ToString("0.##",CultureInfo.InvariantCulture)} {units[unit]}";}
    public async Task ApplyCleanupResultAsync(string result){LastResult=result;await LoadOperationHistoryAsync();}
    public async Task LoadOperationHistoryAsync(CancellationToken token=default){if(audit is null)return;try{var records=await audit.ReadAsync(terminal.Id,100,token);OperationHistory.Clear();foreach(var record in records)OperationHistory.Add(new(record.Timestamp.ToLocalTime(),record.Operation,record.Outcome.ToString(),record.Message??FormatAuditResult(record)));}catch(OperationCanceledException)when(token.IsCancellationRequested){throw;}catch(Exception){}}
    internal void ApplyRefreshSnapshot(TerminalRowViewModel snapshot){State=snapshot.State;ProcessId=snapshot.ProcessId;Error=snapshot.Error;Account=snapshot.Account;AccountSummary=snapshot.AccountSummary;AlgoSummary=snapshot.AlgoSummary;BridgeInstallSummary=snapshot.BridgeInstallSummary;IsBridgeInstallVisible=snapshot.IsBridgeInstallVisible;OperationHistory.Clear();foreach(var entry in snapshot.OperationHistory)OperationHistory.Add(entry);}
    static string FormatAuditResult(AuditRecord record)=>record.CategoryOutcomes.Count==0?record.Outcome.ToString():$"{record.CategoryOutcomes.Sum(x=>x.DeletedFiles):N0} files deleted";
    async Task SetAlgoAsync(bool enable,CancellationToken token)=>await Run(async()=>{try{var operation=await algo!.SetAsync(new(terminal.Id,enable,AlgoOperationSource.Wpf),token);var result=operation.Result;if(result.Snapshot is not null){Account=result.Snapshot;ProjectRuntimeState();}if(!result.Success)throw new InvalidOperationException(result.Message);LastResult=result.Message;}finally{try{await LoadOperationHistoryAsync(token);}catch{}}},token);
    void ProjectRuntimeState(){var a=Account;AccountSummary=a is null?"Bridge unavailable":$"{a.Login} · {a.AccountName} · {a.Server} · {a.TradeMode}";AlgoSummary=a is null?"Algo Trading unknown":$"Global {a.GlobalAlgoTrading} · EA {(a.EaTradingAllowed?"allowed":"denied")} · Account {(a.AccountTradingAllowed?"allowed":"denied")} · Expert {(a.AccountExpertAllowed?"allowed":"denied")} · {(a.Connected?"connected":"disconnected")}";}
    void ProjectBridgeState(BridgeInstallationStatus? status){IsBridgeInstallVisible=status?.State!=BridgeInstallationState.Installed;BridgeInstallSummary=status?.State switch{BridgeInstallationState.Installed=>"Bridge installed and compiled",BridgeInstallationState.NotCompiled=>"Bridge source installed · not compiled",BridgeInstallationState.SourceOutdated=>"Bridge source is outdated",BridgeInstallationState.NotInstalled=>"Bridge not installed",_=>"Bridge installation unavailable"};}
    async Task RefreshActualStateAsync(){var current=await process.GetStateAsync(terminal,CancellationToken.None);State=current.State;ProcessId=current.ProcessId;}
    async Task Run(Func<Task> operation,CancellationToken token=default,bool preserveLastResult=false,string? operationName=null){if(IsBusy)return;IsBusy=true;Error=null;try{await operation();if(operationName is not null)await RecordOperationAsync(operationName,AuditOutcome.Completed,LastResult);}catch(OperationCanceledException)when(token.IsCancellationRequested){throw;}catch(Exception ex){Error=ex.Message;if(!preserveLastResult)LastResult=$"Failed: {ex.Message}";if(operationName is not null)await RecordOperationAsync(operationName,AuditOutcome.Rejected,ex.Message);}finally{IsBusy=false;}}
    async Task RecordOperationAsync(string operation,AuditOutcome outcome,string? message){if(audit is null)return;try{await audit.AppendAsync(new(DateTimeOffset.UtcNow,terminal.Id,terminal.DisplayName,operation,[],State==TerminalState.Running,ShutdownMethod.None,outcome,message,[],false,null));await LoadOperationHistoryAsync();}catch(Exception){}}
}
public sealed record OperationLogEntry(DateTimeOffset Timestamp,string Operation,string Outcome,string Message);
public sealed record BatchSessionResult(string TerminalName,string Outcome,string Message);
