using System.Globalization;
using System.Collections.ObjectModel;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Mt5Manager.Application.Abstractions;
using Mt5Manager.Domain.Models;
namespace Mt5Manager.Wpf.ViewModels;
public sealed partial class MainViewModel(ITerminalDiscovery discovery,ITerminalRegistry registry,ITerminalProcessController process,ITerminalRuntimeInspector? runtime=null,IAlgoTradingService? algo=null,ITerminalStorageInspector? storage=null,IAuditLogger? audit=null):ObservableObject
{
 readonly List<TerminalRowViewModel> all=[];CancellationTokenSource? refresh;int stateRefreshActive;
 [ObservableProperty]string searchText="";[ObservableProperty]bool isRefreshing;[ObservableProperty]string? error;[ObservableProperty]TerminalRowViewModel? selectedTerminal;
 public ObservableCollection<TerminalRowViewModel> Terminals{get;}=[];
 partial void OnSearchTextChanged(string value)=>ApplyFilter();
    [RelayCommand]public async Task RefreshAsync(){refresh?.Cancel();refresh?.Dispose();refresh=new();IsRefreshing=true;Error=null;var selectedId=SelectedTerminal?.Terminal.Id;try{var found=await discovery.DiscoverAsync(refresh.Token);var existing=all.ToDictionary(x=>x.Terminal.Id);var rows=found.Select(x=>existing.TryGetValue(x.Id,out var row)&&RegistrationsEqual(row.Terminal,x)?row:new TerminalRowViewModel(x,process,runtime,algo,storage,audit)).ToArray();await Task.WhenAll(rows.Select(async x=>{await x.RefreshStateAsync(refresh.Token);await x.LoadOperationHistoryAsync(refresh.Token);}));all.Clear();all.AddRange(rows);ApplyFilter(selectedId);}catch(OperationCanceledException){}catch(Exception ex){Error=ex.Message;}finally{IsRefreshing=false;}}
 static bool RegistrationsEqual(TerminalRegistration left,TerminalRegistration right)=>left.Id==right.Id&&left.DisplayName==right.DisplayName&&left.ExecutablePath==right.ExecutablePath&&left.DataDirectory==right.DataDirectory&&left.WorkingDirectory==right.WorkingDirectory&&left.Arguments.SequenceEqual(right.Arguments)&&left.Source==right.Source&&left.DataDirectoryVerified==right.DataDirectoryVerified;
 void ApplyFilter(Guid? preferredId=null){var selectedId=preferredId??SelectedTerminal?.Terminal.Id;Terminals.Clear();foreach(var row in all.Where(x=>string.IsNullOrWhiteSpace(SearchText)||x.DisplayName.Contains(SearchText,StringComparison.OrdinalIgnoreCase)||x.ExecutablePath.Contains(SearchText,StringComparison.OrdinalIgnoreCase)))Terminals.Add(row);SelectedTerminal=Terminals.FirstOrDefault(x=>x.Terminal.Id==selectedId)??Terminals.FirstOrDefault();}
 public async Task AddManualAsync(TerminalRegistration terminal){try{var items=(await registry.LoadAsync()).Where(x=>x.Id!=terminal.Id).Append(terminal).ToArray();await registry.SaveAsync(items);}catch(Exception ex){Error=$"The terminal could not be registered: {ex.Message}";return;}await RefreshAsync();}public void CancelRefresh()=>refresh?.Cancel();
    public async Task RefreshStatesAsync(CancellationToken token=default){if(Interlocked.CompareExchange(ref stateRefreshActive,1,0)!=0)return;try{foreach(var row in all.ToArray()){bool cancelled;try{cancelled=token.IsCancellationRequested;}catch(ObjectDisposedException){cancelled=true;}if(cancelled)return;try{await row.RefreshStateAsync(token);}catch(OperationCanceledException){return;}catch(ObjectDisposedException){return;}}}finally{Volatile.Write(ref stateRefreshActive,0);}}
}
public sealed partial class TerminalRowViewModel(TerminalRegistration terminal,ITerminalProcessController process,ITerminalRuntimeInspector? runtime=null,IAlgoTradingService? algo=null,ITerminalStorageInspector? storage=null,IAuditLogger? audit=null):ObservableObject
{
    public TerminalRegistration Terminal=>terminal;public string DisplayName=>terminal.DisplayName;public string ExecutablePath=>terminal.ExecutablePath;public string DataDirectory=>terminal.DataDirectory;
    public string GlobalAlgoTradingWarning=>"Global Algo Trading affects every EA in this terminal.";
    public ObservableCollection<OperationLogEntry> OperationHistory{get;}=[];
    [ObservableProperty][NotifyCanExecuteChangedFor(nameof(StartCommand),nameof(StopCommand),nameof(RestartCommand),nameof(EnableAlgoCommand),nameof(DisableAlgoCommand))]TerminalState state=TerminalState.Busy;
    [ObservableProperty][NotifyCanExecuteChangedFor(nameof(StartCommand),nameof(StopCommand),nameof(RestartCommand),nameof(EnableAlgoCommand),nameof(DisableAlgoCommand),nameof(InspectStorageCommand))][NotifyPropertyChangedFor(nameof(CanCleanup),nameof(CanInspectStorage),nameof(CanEnableAlgo),nameof(CanDisableAlgo))]bool isBusy;
    [ObservableProperty][NotifyCanExecuteChangedFor(nameof(EnableAlgoCommand),nameof(DisableAlgoCommand))]TerminalAccountSnapshot? account;
    [ObservableProperty]string? error;[ObservableProperty]int? processId;[ObservableProperty]string storageSummary="Storage not inspected";[ObservableProperty]string lastResult="No operations yet";
    [ObservableProperty]string accountSummary="Bridge unavailable";[ObservableProperty]string algoSummary="Algo Trading unknown";
    public bool CanStart=>!IsBusy&&State is TerminalState.Stopped or TerminalState.Error;public bool CanStop=>!IsBusy&&terminal.DataDirectoryVerified&&!string.IsNullOrWhiteSpace(terminal.DataDirectory)&&State==TerminalState.Running;public bool CanRestart=>CanStop;public bool CanCleanup=>!IsBusy&&terminal.DataDirectoryVerified&&!string.IsNullOrWhiteSpace(terminal.DataDirectory);public bool CanInspectStorage=>!IsBusy&&terminal.DataDirectoryVerified&&storage is not null;
    public bool CanEnableAlgo=>CanControlAlgo&&Account?.GlobalAlgoTrading is AlgoTradingState.Disabled;
    public bool CanDisableAlgo=>CanControlAlgo&&Account?.GlobalAlgoTrading is AlgoTradingState.Enabled;
    bool CanControlAlgo=>!IsBusy&&State==TerminalState.Running&&runtime is not null&&algo is not null&&terminal.DataDirectoryVerified&&Account is not null&&Account.GlobalAlgoTrading!=AlgoTradingState.Unknown;
    [RelayCommand(CanExecute=nameof(CanStart))]public async Task StartAsync()=>await Run(async()=>{ProcessId=await process.StartAsync(terminal,CancellationToken.None);State=TerminalState.Running;LastResult="Terminal started.";},operationName:"Start");
    [RelayCommand(CanExecute=nameof(CanStop))]public async Task StopAsync()=>await Run(async()=>{var r=await process.StopAsync(terminal,TimeSpan.FromSeconds(15),false,CancellationToken.None);if(r.Outcome is StopOutcome.ExitedGracefully or StopOutcome.AlreadyStopped or StopOutcome.ForceTerminated){State=TerminalState.Stopped;ProcessId=null;LastResult=r.Outcome.ToString();return;}await RefreshActualStateAsync();throw new InvalidOperationException(r.Error??$"Terminal stop {r.Outcome.ToString().ToLowerInvariant()}.");},operationName:"Stop");
    [RelayCommand(CanExecute=nameof(CanRestart))]public async Task RestartAsync()=>await Run(async()=>{var stopped=await process.StopAsync(terminal,TimeSpan.FromSeconds(15),false,CancellationToken.None);if(stopped.Outcome is not (StopOutcome.ExitedGracefully or StopOutcome.AlreadyStopped or StopOutcome.ForceTerminated)){await RefreshActualStateAsync();throw new InvalidOperationException(stopped.Error??$"Terminal stop {stopped.Outcome.ToString().ToLowerInvariant()}; restart canceled.");}ProcessId=await process.StartAsync(terminal,CancellationToken.None);State=TerminalState.Running;LastResult="Terminal restarted.";},operationName:"Restart");
    [RelayCommand(CanExecute=nameof(CanEnableAlgo))]public async Task EnableAlgoAsync(CancellationToken token=default)=>await SetAlgoAsync(true,token);
    [RelayCommand(CanExecute=nameof(CanDisableAlgo))]public async Task DisableAlgoAsync(CancellationToken token=default)=>await SetAlgoAsync(false,token);
    [RelayCommand]public Task RefreshStateAsync()=>RefreshStateAsync(CancellationToken.None);
    [RelayCommand(CanExecute=nameof(CanInspectStorage))]public async Task InspectStorageAsync()=>await RunStorageInspectionAsync();
    public async Task RefreshStateAsync(CancellationToken token)=>await Run(async()=>{var s=await process.GetStateAsync(terminal,token);State=s.State;ProcessId=s.ProcessId;Error=s.Error;if(runtime is not null){Account=await runtime.ReadAsync(terminal,token);ProjectRuntimeState();}},token);
    public async Task RunStorageInspectionAsync(){if(storage is null)return;await Run(async()=>ApplyStorageInspection(await storage.InspectAsync(terminal,CancellationToken.None)),preserveLastResult:true);}
    public void ApplyStorageInspection(IReadOnlyList<CategoryUsage> usage)=>StorageSummary=string.Join(" · ",usage.Select(x=>$"{x.Category}: {x.FileCount:N0} files, {FormatStorageSize(x.Bytes)}"));
    public static string FormatStorageSize(long bytes){string[] units=["B","KB","MB","GB"];var value=(decimal)bytes;var unit=0;while(value>=1024&&unit<units.Length-1){value/=1024;unit++;}return unit==0?$"{bytes} B":$"{value.ToString("0.##",CultureInfo.InvariantCulture)} {units[unit]}";}
    public async Task ApplyCleanupResultAsync(string result){LastResult=result;await LoadOperationHistoryAsync();}
    public async Task LoadOperationHistoryAsync(CancellationToken token=default){if(audit is null)return;try{var records=await audit.ReadAsync(terminal.Id,100,token);OperationHistory.Clear();foreach(var record in records)OperationHistory.Add(new(record.Timestamp.ToLocalTime(),record.Operation,record.Outcome.ToString(),record.Message??FormatAuditResult(record)));}catch(OperationCanceledException)when(token.IsCancellationRequested){throw;}catch(Exception){}}
    static string FormatAuditResult(AuditRecord record)=>record.CategoryOutcomes.Count==0?record.Outcome.ToString():$"{record.CategoryOutcomes.Sum(x=>x.DeletedFiles):N0} files deleted";
    async Task SetAlgoAsync(bool enable,CancellationToken token)=>await Run(async()=>{try{var operation=await algo!.SetAsync(new(terminal.Id,enable,AlgoOperationSource.Wpf),token);var result=operation.Result;if(result.Snapshot is not null){Account=result.Snapshot;ProjectRuntimeState();}if(!result.Success)throw new InvalidOperationException(result.Message);LastResult=result.Message;}finally{try{await LoadOperationHistoryAsync(token);}catch{}}},token);
    void ProjectRuntimeState(){var a=Account;AccountSummary=a is null?"Bridge unavailable":$"{a.Login} · {a.AccountName} · {a.Server} · {a.TradeMode}";AlgoSummary=a is null?"Algo Trading unknown":$"Global {a.GlobalAlgoTrading} · EA {(a.EaTradingAllowed?"allowed":"denied")} · Account {(a.AccountTradingAllowed?"allowed":"denied")} · Expert {(a.AccountExpertAllowed?"allowed":"denied")} · {(a.Connected?"connected":"disconnected")}";}
    async Task RefreshActualStateAsync(){var current=await process.GetStateAsync(terminal,CancellationToken.None);State=current.State;ProcessId=current.ProcessId;}
    async Task Run(Func<Task> operation,CancellationToken token=default,bool preserveLastResult=false,string? operationName=null){if(IsBusy)return;IsBusy=true;Error=null;try{await operation();if(operationName is not null)await RecordOperationAsync(operationName,AuditOutcome.Completed,LastResult);}catch(OperationCanceledException)when(token.IsCancellationRequested){throw;}catch(Exception ex){Error=ex.Message;if(!preserveLastResult)LastResult=$"Failed: {ex.Message}";if(operationName is not null)await RecordOperationAsync(operationName,AuditOutcome.Rejected,ex.Message);}finally{IsBusy=false;}}
    async Task RecordOperationAsync(string operation,AuditOutcome outcome,string? message){if(audit is null)return;try{await audit.AppendAsync(new(DateTimeOffset.UtcNow,terminal.Id,terminal.DisplayName,operation,[],State==TerminalState.Running,ShutdownMethod.None,outcome,message,[],false,null));await LoadOperationHistoryAsync();}catch(Exception){}}
}
public sealed record OperationLogEntry(DateTimeOffset Timestamp,string Operation,string Outcome,string Message);
