<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Mt5Manager.Domain\Mt5Manager.Domain.csproj" />
    <ProjectReference Include="..\Mt5Manager.Application\Mt5Manager.Application.csproj" />
    <ProjectReference Include="..\Mt5Manager.Infrastructure\Mt5Manager.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\Mt5Manager.Mql5\Experts\Mt5ManagerBridge.mq5" Link="Mt5ManagerBridge.mq5">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
    <Resource Include="Assets\mt5-manager.ico" />
    <Resource Include="Assets\mt5-manager-logo.png" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\mt5-manager.ico</ApplicationIcon>
    <Version>1.2.1</Version>
    <AssemblyVersion>1.2.1.0</AssemblyVersion>
    <FileVersion>1.2.1.0</FileVersion>
  </PropertyGroup>

</Project>
